name: Validate & Deploy Streamlit App

on:
  push:
    branches: [ main ]          # or 'master', adjust if needed
  workflow_dispatch:            # allow manual runs from the Actions tab

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"           # ⟵ match Streamlit Cloud default
      STREAMLIT_CLOUD_APP_URL: ${{ secrets.STREAMLIT_CLOUD_APP_URL }}
      STREAMLIT_CLOUD_TOKEN:   ${{ secrets.STREAMLIT_CLOUD_TOKEN }}

    steps:
    #------------------------------------------------------------
    # 1.  Checkout the repo
    #------------------------------------------------------------
    - name: Checkout source
      uses: actions/checkout@v4

    #------------------------------------------------------------
    # 2.  Set up Python & cache dependencies
    #------------------------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    #------------------------------------------------------------
    # 3.  Install dependencies
    #------------------------------------------------------------
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #------------------------------------------------------------
    # 4.  Smoke‑test: does the app start?
    #------------------------------------------------------------
    - name: Run Streamlit smoke test
      run: |
        timeout 30 streamlit run streamlit_app.py --server.headless true &
        PID=$!
        sleep 15
        # curl localhost:8501 just to make sure port is listening
        if curl -s http://localhost:8501/healthz | grep -q "ok"; then
          echo "✅ Streamlit app started"
          kill $PID
        else
          echo "❌ Streamlit app did NOT start" && kill $PID && exit 1
        fi

    #------------------------------------------------------------
    # 5.  Trigger Streamlit Cloud redeploy (optional but nice)
    #------------------------------------------------------------
    - name: Trigger Streamlit Cloud redeploy
      if: env.STREAMLIT_CLOUD_APP_URL != ''
      run: |
        curl -X POST \
          -H "Authorization: Bearer $STREAMLIT_CLOUD_TOKEN" \
          -H "Content-Type: application/json" \
          "$STREAMLIT_CLOUD_APP_URL/api/v1/sync"

